// <auto-generated />
using System;
using Flowenter.Parties.Mappings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flowenter.Parties.Mappings.Migrations
{
    [DbContext(typeof(PartiesContext))]
    [Migration("20251107070819_initParties")]
    partial class initParties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("parties")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("ContactMechanisms", "parties");

                    b.HasDiscriminator().HasValue("ContactMechanism");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanismType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ContactMechanismTypes", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FinancialAccountModels.FinancialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Number")
                        .IsUnique();

                    b.ToTable("FinancialAccounts", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("GeographicBoundaries", "parties");

                    b.HasDiscriminator().HasValue("GeographicBoundary");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundaryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GeographicBoundaryTypes", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.LegalStructure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LegalStructures", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Parties", "parties");

                    b.HasDiscriminator().HasValue("Party");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("GroupById")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("GroupById");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PartyCategories", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PartyId");

                    b.ToTable("PartyClassifications", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyContactMechanism", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactMechanismId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartyRoleTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateOnly?>("ThruDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ContactMechanismId");

                    b.HasIndex("PartyRoleTypeId");

                    b.HasIndex("PartyId", "PartyRoleTypeId", "ContactMechanismId", "FromDate")
                        .IsUnique();

                    b.ToTable("PartyContactMechanisms", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateOnly?>("ThruDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("TypeId", "PartyId", "FromDate")
                        .IsUnique();

                    b.ToTable("PartyRoles", "parties");

                    b.HasDiscriminator().HasValue("PartyRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyRoleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PartyRoleTypes", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PartyTypes", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.ElectronicAddress", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasIndex("Address");

                    b.HasDiscriminator().HasValue("ElectronicAddress");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.PostalAddress", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("City")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("District")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("House")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Province")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("State")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Street")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SubDistrict")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasIndex("CountryId");

                    b.ToTable("ContactMechanisms", "parties", t =>
                        {
                            t.Property("Address")
                                .HasColumnName("PostalAddress_Address");
                        });

                    b.HasDiscriminator().HasValue("PostalAddress");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.TelecommunicationNumber", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism");

                    b.Property<string>("AreaCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("AskForName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasIndex("CountryId", "Number")
                        .IsUnique();

                    b.ToTable("ContactMechanisms", "parties", t =>
                        {
                            t.Property("CountryId")
                                .HasColumnName("TelecommunicationNumber_CountryId");
                        });

                    b.HasDiscriminator().HasValue("TelecommunicationNumber");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.Country", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundary");

                    b.Property<string>("IsoCode2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("IsoCode3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Country");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Organization", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.PartyModels.Party");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Organization");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Person", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.PartyModels.Party");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasIndex("FirstName", "MiddleName", "LastName")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Person");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Customer", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.PartyModels.PartyRole");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Enterprise", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.PartyModels.PartyRole");

                    b.Property<string>("BrandName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BusinessRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FiscalYearStartMonth")
                        .HasColumnType("integer");

                    b.Property<string>("Information")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("LegalStructureId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("bytea");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasIndex("LegalName")
                        .IsUnique();

                    b.HasIndex("LegalStructureId");

                    b.HasDiscriminator().HasValue("Enterprise");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanismType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FinancialAccountModels.FinancialAccount", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.Party", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundary", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundaryType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Party", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyCategory", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyCategory", "GroupBy")
                        .WithMany()
                        .HasForeignKey("GroupById");

                    b.Navigation("GroupBy");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyClassification", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.PartyModels.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyContactMechanism", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism", "ContactMechanism")
                        .WithMany()
                        .HasForeignKey("ContactMechanismId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.PartyModels.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyRoleType", "PartyRoleType")
                        .WithMany()
                        .HasForeignKey("PartyRoleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactMechanism");

                    b.Navigation("Party");

                    b.Navigation("PartyRoleType");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyRole", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyRoleType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.PostalAddress", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.GeographicBoundaryModels.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.TelecommunicationNumber", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.GeographicBoundaryModels.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Enterprise", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.LegalStructure", "LegalStructure")
                        .WithMany()
                        .HasForeignKey("LegalStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegalStructure");
                });
#pragma warning restore 612, 618
        }
    }
}
