// <auto-generated />
using System;
using Flowenter.Products.Mappings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flowenter.Products.Mappings.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20260715134419_initProducts")]
    partial class initProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("products")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flowenter.Products.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly?>("DiscontinuedDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ProviderPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateOnly?>("SupportDiscontinuedDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "ProviderPartyId")
                        .IsUnique()
                        .HasFilter("[ProviderPartyId] IS NOT NULL");

                    b.ToTable("Products", "products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Flowenter.Products.Models.Good", b =>
                {
                    b.HasBaseType("Flowenter.Products.Models.Product");

                    b.ToTable("Goods", "products");
                });

            modelBuilder.Entity("Flowenter.Products.Models.Service", b =>
                {
                    b.HasBaseType("Flowenter.Products.Models.Product");

                    b.ToTable("Services", "products");
                });

            modelBuilder.Entity("Flowenter.Products.Models.Good", b =>
                {
                    b.HasOne("Flowenter.Products.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Products.Models.Good", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Flowenter.Products.Models.Service", b =>
                {
                    b.HasOne("Flowenter.Products.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Products.Models.Service", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
