// <auto-generated />
using System;
using Flowenter.Products.Mappings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flowenter.Products.Mappings.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20260718114149_addProductCoverImage")]
    partial class addProductCoverImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("products")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flowenter.Products.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CoverImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CoverImageName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly?>("DiscontinuedDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ProviderPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateOnly?>("SupportDiscontinuedDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderPartyId", "Name")
                        .IsUnique()
                        .HasFilter("[ProviderPartyId] IS NOT NULL");

                    b.ToTable("Products", "products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Flowenter.Products.Models.ProductFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("ProductFeatureCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductFeatureType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ProviderPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeatureCategoryId");

                    b.HasIndex("ProviderPartyId", "ProductFeatureType", "ProductFeatureCategoryId", "Code")
                        .IsUnique()
                        .HasFilter("[ProviderPartyId] IS NOT NULL");

                    b.ToTable("ProductFeatures", "products");

                    b.HasDiscriminator<string>("ProductFeatureType").HasValue("ProductFeature");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Flowenter.Products.Models.ProductFeatureApplicability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("ProductFeatureApplicabilityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProductFeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateOnly>("ThruDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeatureId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFeatureApplicabilities", "products");

                    b.HasDiscriminator<string>("ProductFeatureApplicabilityType").HasValue("ProductFeatureApplicability");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Flowenter.Products.Models.ProductFeatureCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ProviderPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderPartyId", "Name")
                        .IsUnique()
                        .HasFilter("[ProviderPartyId] IS NOT NULL");

                    b.ToTable("ProductFeatureCategories", "products");
                });

            modelBuilder.Entity("Flowenter.Products.Models.Good", b =>
                {
                    b.HasBaseType("Flowenter.Products.Models.Product");

                    b.ToTable("Goods", "products");
                });

            modelBuilder.Entity("Flowenter.Products.Models.Service", b =>
                {
                    b.HasBaseType("Flowenter.Products.Models.Product");

                    b.ToTable("Services", "products");
                });

            modelBuilder.Entity("Flowenter.Products.Models.ServiceFeature", b =>
                {
                    b.HasBaseType("Flowenter.Products.Models.ProductFeature");

                    b.HasDiscriminator().HasValue("ServiceFeature");
                });

            modelBuilder.Entity("Flowenter.Products.Models.OptionalFeature", b =>
                {
                    b.HasBaseType("Flowenter.Products.Models.ProductFeatureApplicability");

                    b.HasDiscriminator().HasValue("OptionalFeature");
                });

            modelBuilder.Entity("Flowenter.Products.Models.RequiredFeature", b =>
                {
                    b.HasBaseType("Flowenter.Products.Models.ProductFeatureApplicability");

                    b.HasDiscriminator().HasValue("RequiredFeature");
                });

            modelBuilder.Entity("Flowenter.Products.Models.SelectableFeature", b =>
                {
                    b.HasBaseType("Flowenter.Products.Models.ProductFeatureApplicability");

                    b.HasDiscriminator().HasValue("SelectableFeature");
                });

            modelBuilder.Entity("Flowenter.Products.Models.StandardFeature", b =>
                {
                    b.HasBaseType("Flowenter.Products.Models.ProductFeatureApplicability");

                    b.HasDiscriminator().HasValue("StandardFeature");
                });

            modelBuilder.Entity("Flowenter.Products.Models.ProductFeature", b =>
                {
                    b.HasOne("Flowenter.Products.Models.ProductFeatureCategory", "ProductFeatureCategory")
                        .WithMany()
                        .HasForeignKey("ProductFeatureCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFeatureCategory");
                });

            modelBuilder.Entity("Flowenter.Products.Models.ProductFeatureApplicability", b =>
                {
                    b.HasOne("Flowenter.Products.Models.ProductFeature", "ProductFeature")
                        .WithMany()
                        .HasForeignKey("ProductFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Products.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductFeature");
                });

            modelBuilder.Entity("Flowenter.Products.Models.Good", b =>
                {
                    b.HasOne("Flowenter.Products.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Products.Models.Good", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Flowenter.Products.Models.Service", b =>
                {
                    b.HasOne("Flowenter.Products.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Products.Models.Service", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
