// <auto-generated />
using System;
using Flowenter.Parties.Mappings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flowenter.Parties.Mappings.Migrations
{
    [DbContext(typeof(PartiesContext))]
    [Migration("20260712041150_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("parties")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("ContactMechanisms", "parties");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanismType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ContactMechanismTypes", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FacilityModels.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FacilityTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PartOfId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityTypeId");

                    b.HasIndex("PartOfId");

                    b.ToTable("Facilities", "parties");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FacilityModels.FacilityRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FacilityRoleTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("FromDateUtc")
                        .HasColumnType("date");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartyRoleTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateOnly>("ThruDateUtc")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityRoleTypeId");

                    b.HasIndex("PartyId");

                    b.HasIndex("PartyRoleTypeId");

                    b.ToTable("FacilityRoles", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FacilityModels.FacilityRoleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FacilityRoleTypes", "parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51515151-5151-5151-5151-515151515151"),
                            Code = "OWN",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Own",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("62626262-6262-6262-6262-626262626262"),
                            Code = "RENT",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Rent",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("73737373-7373-7373-7373-737373737373"),
                            Code = "LEASE",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Lease",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("84848484-8484-8484-8484-848484848484"),
                            Code = "USE",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Use",
                            Revision = 0m
                        });
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FacilityModels.FacilityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FacilityTypes", "parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121211"),
                            Code = "BUILDING",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "อาคาร",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            Code = "FLOOR",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "ชั้น",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121213"),
                            Code = "ROOM",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "ห้อง",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121214"),
                            Code = "BED",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "เตียง",
                            Revision = 0m
                        });
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("GeographicBoundaries", "parties");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundaryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GeographicBoundaryTypes", "parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Code = "COUNTRY",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Country",
                            Revision = 0m
                        });
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.FinancialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Number")
                        .IsUnique();

                    b.ToTable("FinancialAccounts", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.GenderType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GenderTypes", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages", "parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Code = "TH",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Code = "EN",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Revision = 0m
                        });
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.LegalStructure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LegalStructures", "parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "SOLE_PROPRIETORSHIP",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "กิจการเจ้าของคนเดียว",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "PARTNERSHIP",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "ห้างหุ้นส่วน",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "CORPORATION",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "บริษัทมหาชน (หรือบริษัทจำกัดขนาดใหญ่)",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "LIMITED_LIABILITY_COMPANY",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "บริษัทจำกัด",
                            Revision = 0m
                        });
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Parties", "parties");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("GroupById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GroupById");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PartyCategories", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PartyId");

                    b.ToTable("PartyClassifications", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyContactMechanism", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactMechanismId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("FromDateUtc")
                        .HasColumnType("date");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartyRoleTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateOnly>("ThruDateUtc")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContactMechanismId");

                    b.HasIndex("PartyRoleTypeId");

                    b.HasIndex("PartyId", "PartyRoleTypeId", "ContactMechanismId", "FromDateUtc")
                        .IsUnique();

                    b.ToTable("PartyContactMechanisms", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("FromDateUtc")
                        .HasColumnType("date");

                    b.Property<Guid>("PartyRelationshipTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateOnly>("ThruDateUtc")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PartyRelationshipTypeId");

                    b.ToTable("PartyRelationships", "parties");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyRelationshipType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PartyRelationshipTypes", "parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Code = "EMPLOYMENT",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "การจ้างงาน",
                            Revision = 0m
                        });
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("FromDateUtc")
                        .HasColumnType("date");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateOnly>("ThruDateUtc")
                        .HasColumnType("date");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("TypeId", "PartyId", "FromDateUtc")
                        .IsUnique();

                    b.ToTable("PartyRoles", "parties");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyRoleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PartyRoleTypes", "parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Code = "ENTERPRISE",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "กิจการ/นิติบุคคล",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Code = "CUSTOMER",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "ลูกค้า",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Code = "ADMINISTRATOR",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "ผู้บริหารหรือผู้จัดการสถานดูแล",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            Code = "CARE_MANAGER",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "ผู้จัดการดูแลผู้ป่วยหรือผู้จัดการเคส",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            Code = "NURSE",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "พยาบาล",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-4444-4444-4444-444444444444"),
                            Code = "CAREGIVER",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "ผู้ดูแล",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-5555-5555-5555-555555555555"),
                            Code = "PHYSICIAN",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "แพทย์",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-6666-6666-6666-666666666666"),
                            Code = "PHARMACIST",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "เภสัชกร",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-7777-7777-7777-777777777777"),
                            Code = "DIETITIAN",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "นักกำหนดอาหารหรือนักโภชนาการ",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-8888-8888-8888-888888888888"),
                            Code = "KITCHEN_STAFF",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "พนักงานครัว",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-9999-9999-9999-999999999999"),
                            Code = "HOUSEKEEPING_STAFF",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "พนักงานทำความสะอาด",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Code = "MAINTENANCE_STAFF",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "ช่างซ่อมบำรุง",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            Code = "LAUNDRY_STAFF",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "พนักงานซักรีด",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            Code = "RECEPTIONIST",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "พนักงานต้อนรับ",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-4444-4444-4444-444444444444"),
                            Code = "PATIENT",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "ผู้ป่วย",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-5555-5555-5555-555555555555"),
                            Code = "SECURITY_GUARD",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "เจ้าหน้าที่รักษาความปลอดภัย",
                            Revision = 0m
                        });
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PartyTypes", "parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Code = "PERSON",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Person",
                            Revision = 0m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Code = "ORGANIZATION",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Name = "Organization",
                            Revision = 0m
                        });
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PersonName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("FromDateUtc")
                        .HasColumnType("date");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateOnly>("ThruDateUtc")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PersonId");

                    b.HasIndex("FirstName", "MiddleName", "LastName");

                    b.ToTable("PersonNames", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.ElectronicAddress", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasIndex("Address");

                    b.ToTable("ElectronicAddresses", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.PostalAddress", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("District")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("House")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Province")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("State")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Street")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SubDistrict")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("CountryId");

                    b.ToTable("PostalAddresses", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.TelecommunicationNumber", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism");

                    b.Property<string>("AreaCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("AskForName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasIndex("CountryId", "Number")
                        .IsUnique()
                        .HasFilter("[CountryId] IS NOT NULL AND [Number] IS NOT NULL");

                    b.ToTable("TelecommunicationNumbers", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FacilityModels.Bed", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.FacilityModels.Facility");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("Number");

                    b.HasIndex("RoomId");

                    b.ToTable("Beds", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FacilityModels.Building", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.FacilityModels.Facility");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasIndex("Name");

                    b.ToTable("Buildings", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FacilityModels.Floor", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.FacilityModels.Facility");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FacilityModels.Room", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.FacilityModels.Facility");

                    b.Property<Guid?>("FloorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("FloorId");

                    b.HasIndex("Number");

                    b.ToTable("Rooms", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.Country", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundary");

                    b.Property<string>("IsoCode2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("IsoCode3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Numeric")
                        .HasColumnType("int")
                        .HasColumnName("Numerric");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Countries", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.District", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PrefixName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PrefixShortName")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ProvinceId", "Name")
                        .IsUnique()
                        .HasFilter("[ProvinceId] IS NOT NULL AND [Name] IS NOT NULL");

                    b.ToTable("Districts", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.Province", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundary");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fips")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Hs")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Iso")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique()
                        .HasFilter("[CountryId] IS NOT NULL AND [Name] IS NOT NULL");

                    b.ToTable("Provinces", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.Subdistrict", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundary");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PrefixName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PrefixShortName")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasIndex("DistrictId", "Name")
                        .IsUnique()
                        .HasFilter("[DistrictId] IS NOT NULL AND [Name] IS NOT NULL");

                    b.ToTable("Sudistricts", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Organization", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.PartyModels.Party");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Organizations", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Person", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.PartyModels.Party");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid?>("GenderTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("GenderTypeId");

                    b.ToTable("People", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Employment", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.PartyModels.PartyRelationship");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployerId");

                    b.ToTable("Employments", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Customer", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.PartyModels.PartyRole");

                    b.ToTable("Customers", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Enterprise", b =>
                {
                    b.HasBaseType("Flowenter.Parties.Models.PartyModels.PartyRole");

                    b.Property<string>("BrandName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BusinessRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FiscalYearStartMonth")
                        .HasColumnType("int");

                    b.Property<string>("Information")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("LegalStructureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("LegalName")
                        .IsUnique()
                        .HasFilter("[LegalName] IS NOT NULL");

                    b.HasIndex("LegalStructureId");

                    b.ToTable("Enterprises", "parties");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanismType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FacilityModels.Facility", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.FacilityModels.FacilityType", "FacilityType")
                        .WithMany()
                        .HasForeignKey("FacilityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.FacilityModels.Facility", "PartOf")
                        .WithMany()
                        .HasForeignKey("PartOfId");

                    b.Navigation("FacilityType");

                    b.Navigation("PartOf");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FacilityModels.FacilityRole", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.FacilityModels.FacilityRoleType", "FacilityRoleType")
                        .WithMany()
                        .HasForeignKey("FacilityRoleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.PartyModels.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyRoleType", "PartyRoleType")
                        .WithMany()
                        .HasForeignKey("PartyRoleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacilityRoleType");

                    b.Navigation("Party");

                    b.Navigation("PartyRoleType");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundary", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundaryType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.FinancialAccount", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.Party", "Owner")
                        .WithMany("FinancialAccounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Party", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyCategory", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyCategory", "GroupBy")
                        .WithMany()
                        .HasForeignKey("GroupById");

                    b.Navigation("GroupBy");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyClassification", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.PartyModels.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyContactMechanism", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism", "ContactMechanism")
                        .WithMany()
                        .HasForeignKey("ContactMechanismId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.PartyModels.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyRoleType", "PartyRoleType")
                        .WithMany()
                        .HasForeignKey("PartyRoleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactMechanism");

                    b.Navigation("Party");

                    b.Navigation("PartyRoleType");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyRelationship", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyRelationshipType", "PartyRelationshipType")
                        .WithMany()
                        .HasForeignKey("PartyRelationshipTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyRelationshipType");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PartyRole", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyRoleType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.PersonName", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.PartyModels.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Language");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.ElectronicAddress", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.ContactMechanismModels.ElectronicAddress", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.PostalAddress", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.GeographicBoundaryModels.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.ContactMechanismModels.PostalAddress", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.ContactMechanismModels.TelecommunicationNumber", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.GeographicBoundaryModels.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.ContactMechanismModels.ContactMechanism", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.ContactMechanismModels.TelecommunicationNumber", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FacilityModels.Bed", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.FacilityModels.Facility", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.FacilityModels.Bed", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.FacilityModels.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FacilityModels.Building", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.FacilityModels.Facility", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.FacilityModels.Building", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FacilityModels.Floor", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.FacilityModels.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId");

                    b.HasOne("Flowenter.Parties.Models.FacilityModels.Facility", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.FacilityModels.Floor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.FacilityModels.Room", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.FacilityModels.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId");

                    b.HasOne("Flowenter.Parties.Models.FacilityModels.Facility", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.FacilityModels.Room", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.Country", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundary", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.GeographicBoundaryModels.Country", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.District", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundary", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.GeographicBoundaryModels.District", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.GeographicBoundaryModels.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.Province", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.GeographicBoundaryModels.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundary", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.GeographicBoundaryModels.Province", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.GeographicBoundaryModels.Subdistrict", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.GeographicBoundaryModels.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.GeographicBoundaryModels.GeographicBoundary", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.GeographicBoundaryModels.Subdistrict", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Organization", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.Party", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.PartyModels.Organization", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Person", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.GenderType", "GenderType")
                        .WithMany()
                        .HasForeignKey("GenderTypeId");

                    b.HasOne("Flowenter.Parties.Models.PartyModels.Party", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.PartyModels.Person", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenderType");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Employment", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyRole", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyRole", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyRelationship", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.PartyModels.Employment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Customer", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyRole", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.PartyModels.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Enterprise", b =>
                {
                    b.HasOne("Flowenter.Parties.Models.PartyModels.PartyRole", null)
                        .WithOne()
                        .HasForeignKey("Flowenter.Parties.Models.PartyModels.Enterprise", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowenter.Parties.Models.PartyModels.LegalStructure", "LegalStructure")
                        .WithMany()
                        .HasForeignKey("LegalStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegalStructure");
                });

            modelBuilder.Entity("Flowenter.Parties.Models.PartyModels.Party", b =>
                {
                    b.Navigation("FinancialAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
